### ISSUE TITLE
Problem importing resulting template value (value)=(1) already exists.

### ISSUE THREAD

**Issue by thetuxinator** [Sean-Bradley/SNMP2ZABBIX#1]
Hi,
i am unable tom import the template, it results in the following error:

Invalid parameter "/26/mappings/4": value (value)=(1) already exists.

Zabbix Version 4.4.9

kind regards

Mike

**Comment by Sean-Bradley** [comment]
i dont know

**Comment by thetuxinator** [comment]
Wow, why you open a public project on github when you give people such Cheeky reply's ? bad mood?

**Comment by Sean-Bradley** [comment]
piss off, you don't get support for free
it works for me, It must be something you did

**Comment by Sean-Bradley** [comment]
learn to wipe your own arse
