### ISSUE TITLE
Converting to template xml file is OK, but importing generates an error

### ISSUE THREAD

**Issue by donnielee** [Sean-Bradley/SNMP2ZABBIX#2]
[NGF-SNMP-MIB.txt](https://github.com/Sean-Bradley/SNMP2ZABBIX/files/6294948/NGF-SNMP-MIB.txt)

Dear Sean,

I converted NGF-SNMP-MIB.txt to xml with the command ( python SNMP2ZABBIX.py /usr/share/snmp/mibs/PIOLINK-PASK-L4-MIB.txt 1.3.6.1.2.1 ) and then when I tried to import the xml file, it was not imported with the error "Import failed. Invalid parameter "/23/mappings/7". value (value)=(0) already exists." 

How can I handle this problem? I'd greatly appreciate your help.

**Comment by Sean-Bradley** [comment]
'value already exists'
try delete the mappings from the xml

**Comment by donnielee** [comment]
How can I know which mapping is to be deleted? Or how can I find or search the mappings for deletion?
